[package]
name = "native_functions"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmedge-bindgen = "0.4.1"
wasmedge-bindgen-macro = "0.4.1"
proc-macro2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
uint = {version = "0.9", features = ["std"] }

[build-dependencies]
cc = "1.0"